services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_pass
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    image: wordpress:5.4.2-php7.2-apache
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_pass
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - ./html:/var/www/html

  nginx:
    image: nginx:1.19.0
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html

  locust:
    image: locustio/locust:2.31.3
    depends_on:
      - nginx
    environment:
      - LOCUST_OPTS=--host=http://nginx:80
      - POST_PATH=/
    volumes:
      - ./loadtest:/home/locust
      - ./results:/results
    ports:
      - "8089:8089"
    command: >
      -f /home/locust/locustfile.py
      --web-host=0.0.0.0

volumes:
  db_data:
