version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_pass
    volumes:
      - db_data:/var/lib/mysql

  wordpress1:
    image: wordpress:5.4.2-php7.2-apache
    container_name: wordpress1
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_pass
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - ./html:/var/www/html

  wordpress2:
    image: wordpress:5.4.2-php7.2-apache
    container_name: wordpress2
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_pass
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - ./html:/var/www/html

  wordpress3:
    image: wordpress:5.4.2-php7.2-apache
    container_name: wordpress3
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_pass
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - ./html:/var/www/html

  nginx:
    image: nginx:1.19.0
    container_name: nginx
    depends_on:
      - wordpress1
      - wordpress2
      - wordpress3
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html

volumes:
  db_data:
